# Generated by Django 5.2.17 on 2026-08-26 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GABINETE", "Gabinete"),
                            ("MONITOR", "Monitor"),
                            ("TECLADO", "Teclado"),
                            ("MESA", "Mesa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text='Ex.: "WORKSTATION CORPORATIVO", "MONITOR DE VÍDEO 24" DELL"',
                        max_length=200,
                    ),
                ),
                (
                    "numero_patrimonio",
                    models.CharField(
                        blank=True,
                        help_text="Número do inventário patrimonial oficial do SENAI. Em branco para teclados (não constam no inventário oficial).",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "codigo_qr",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único gerado pelo sistema — é o que vira o QR Code colado no ativo.",
                        unique=True,
                    ),
                ),
                ("sala", models.CharField(default="B-111", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("EM_MANUTENCAO", "Em manutenção"),
                            ("DEVOLVIDO", "Devolvido"),
                        ],
                        default="ATIVO",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tipo", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoMovimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("CADASTRO", "Cadastro"),
                            ("ENTREGA", "Entrega"),
                            ("DEVOLUCAO", "Devolução"),
                            ("MANUTENCAO", "Manutenção"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="ativos.ativo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
